#!/usr/bin/env python3
"""
Generate MiniZinc graph-coloring models from mandala regions/adjacency JSON files.

Expected assets under resources/assets/<id>/:
- mandala_<id>_regions.json (or legacy mandala_1.json)
- mandala_<id>_adjacency.json
- (optional hard) mandala_<id>_adjacency-hard.json / mandala_<id>_adjacency_hard.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable, List, Sequence, Set, Tuple


Edge = Tuple[int, int]


def parse_region_ids(regions_json_path: Path) -> Set[int]:
    data = json.loads(regions_json_path.read_text(encoding="utf-8"))

    if isinstance(data, dict):
        regions = data.get("regions", [])
    elif isinstance(data, list):
        regions = data
    else:
        raise ValueError(f"Invalid regions JSON root in {regions_json_path}")

    ids: Set[int] = set()
    for index, region in enumerate(regions):
        if not isinstance(region, dict):
            continue
        region_id = region.get("id", index)
        if isinstance(region_id, int):
            ids.add(region_id)

    return ids


def parse_adjacency_edges(adjacency_json_path: Path) -> Set[Edge]:
    data = json.loads(adjacency_json_path.read_text(encoding="utf-8"))

    if isinstance(data, dict):
        pairs = data.get("pairs", [])
    elif isinstance(data, list):
        pairs = data
    else:
        raise ValueError(f"Invalid adjacency JSON root in {adjacency_json_path}")

    edges: Set[Edge] = set()
    for pair in pairs:
        if not isinstance(pair, list) or len(pair) < 2:
            continue

        a = pair[0]
        b = pair[1]
        if not isinstance(a, int) or not isinstance(b, int) or a == b:
            continue

        edges.add((a, b) if a < b else (b, a))

    return edges


def find_mandala_ids(assets_root: Path) -> List[int]:
    ids: List[int] = []
    for child in assets_root.iterdir():
        if not child.is_dir() or not child.name.isdigit():
            continue

        mandala_id = int(child.name)
        has_regions = (child / f"mandala_{mandala_id}_regions.json").exists() or bool(list(child.glob("mandala_*.json")))
        has_adjacency = (child / f"mandala_{mandala_id}_adjacency.json").exists() or bool(list(child.glob("*adjacency*.json")))
        if has_regions and has_adjacency:
            ids.append(mandala_id)

    return sorted(ids)


def find_regions_file(asset_dir: Path, mandala_id: int) -> Path:
    preferred = asset_dir / f"mandala_{mandala_id}_regions.json"
    if preferred.exists():
        return preferred

    legacy = sorted(path for path in asset_dir.glob("mandala_*.json") if "adjacency" not in path.name)
    if not legacy:
        raise FileNotFoundError(f"No regions JSON found in {asset_dir}")
    return legacy[0]


def find_adjacency_file(asset_dir: Path, mandala_id: int, hard_mode: bool = False) -> Path:
    if hard_mode:
        preferred_candidates = [
            asset_dir / f"mandala_{mandala_id}_adjacency-hard.json",
            asset_dir / f"mandala_{mandala_id}_adjacency_hard.json",
        ]
        for preferred in preferred_candidates:
            if preferred.exists():
                return preferred

        candidates = sorted(
            path for path in asset_dir.glob("*adjacency*.json") if "hard" in path.stem.lower()
        )
        if not candidates:
            raise FileNotFoundError(f"No hard adjacency JSON found in {asset_dir}")
        return candidates[0]

    preferred = asset_dir / f"mandala_{mandala_id}_adjacency.json"
    if preferred.exists():
        return preferred

    candidates = sorted(
        path for path in asset_dir.glob("*adjacency*.json") if "hard" not in path.stem.lower()
    )
    if not candidates:
        raise FileNotFoundError(f"No adjacency JSON found in {asset_dir}")
    return candidates[0]


def infer_output_filename(asset_dir: Path, mandala_id: int, hard_mode: bool = False) -> str:
    regions_path = find_regions_file(asset_dir, mandala_id)
    suffix = "_hard" if hard_mode else ""
    return regions_path.stem + suffix + ".mzn"


def has_hard_adjacency_file(asset_dir: Path, mandala_id: int) -> bool:
    try:
        find_adjacency_file(asset_dir, mandala_id, hard_mode=True)
        return True
    except FileNotFoundError:
        return False


def format_int_set(values: Sequence[int]) -> str:
    return "{" + ", ".join(str(value) for value in values) + "}"


def format_int_array(values: Sequence[int]) -> str:
    return "[" + ", ".join(str(value) for value in values) + "]"


def build_minizinc_model(region_ids: Sequence[int], edges: Sequence[Edge], source_note: str) -> str:
    if not region_ids:
        raise ValueError("No region ids found.")

    first_region = region_ids[0]
    edge_u = [edge[0] for edge in edges]
    edge_v = [edge[1] for edge in edges]

    lines: List[str] = []
    lines.append(f"% Auto-generated by tools/generate_minizinc.py from {source_note}")
    lines.append("% Objective: minimize number of colors used for the mandala graph.")
    lines.append("")
    lines.append(f"set of int: REGIONS = {format_int_set(region_ids)};")
    lines.append(f"int: REGION_COUNT = {len(region_ids)};")
    lines.append(f"int: EDGE_COUNT = {len(edges)};")
    lines.append("")
    lines.append("array[REGIONS] of var 1..REGION_COUNT: color;")
    lines.append("var 1..REGION_COUNT: max_color;")
    lines.append("")

    if edges:
        lines.append("array[1..EDGE_COUNT] of int: edge_u = " + format_int_array(edge_u) + ";")
        lines.append("array[1..EDGE_COUNT] of int: edge_v = " + format_int_array(edge_v) + ";")
        lines.append("")
        lines.append("constraint forall(e in 1..EDGE_COUNT)(color[edge_u[e]] != color[edge_v[e]]);")

    lines.append("constraint forall(r in REGIONS)(color[r] <= max_color);")
    lines.append(f"constraint color[{first_region}] = 1;")
    lines.append("")
    lines.append("solve :: int_search([color[r] | r in REGIONS], first_fail, indomain_min, complete) minimize max_color;")
    lines.append("")
    lines.append(
        'output ["min_colors=", show(max_color), "\\n", '
        '"colors=", show([color[r] | r in REGIONS]), "\\n"];'
    )

    return "\n".join(lines) + "\n"


def process_mandala(assets_root: Path, mandala_id: int, output_name: str | None, hard_mode: bool = False) -> Path:
    asset_dir = assets_root / str(mandala_id)
    asset_dir.mkdir(parents=True, exist_ok=True)

    regions_json = find_regions_file(asset_dir, mandala_id)
    adjacency_json = find_adjacency_file(asset_dir, mandala_id, hard_mode=hard_mode)

    region_ids = parse_region_ids(regions_json)
    edges = parse_adjacency_edges(adjacency_json)

    ids_from_edges = {id_value for edge in edges for id_value in edge}
    all_ids = sorted(region_ids | ids_from_edges)
    sorted_edges = sorted(edges)

    output_filename = output_name if output_name else infer_output_filename(asset_dir, mandala_id, hard_mode)
    output_path = asset_dir / output_filename

    source_note = f"{regions_json} and {adjacency_json}"
    model = build_minizinc_model(all_ids, sorted_edges, source_note)
    output_path.write_text(model, encoding="utf-8")

    return output_path


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent

    parser = argparse.ArgumentParser(
        description="Generate MiniZinc models for mandala graph coloring from JSON assets."
    )
    parser.add_argument(
        "--assets-root",
        type=Path,
        default=project_root / "resources" / "assets",
        help="Path to resources/assets (default: project resources/assets)",
    )
    parser.add_argument(
        "--mandala-id",
        type=int,
        action="append",
        help="Mandala id to process. Repeat option to process multiple ids.",
    )
    parser.add_argument(
        "--output-name",
        type=str,
        help="Optional output filename for single-id generation (example: mandala_1.mzn)",
    )
    parser.add_argument(
        "--include-hard",
        action="store_true",
        help="Also generate *_hard.mzn when a hard adjacency JSON exists.",
    )
    parser.add_argument(
        "--hard-only",
        action="store_true",
        help="Generate only hard-mode MiniZinc files (requires hard adjacency JSON).",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    assets_root: Path = args.assets_root.resolve()

    if not assets_root.exists():
        raise FileNotFoundError(f"Assets root does not exist: {assets_root}")

    selected_ids: Iterable[int]
    if args.mandala_id:
        selected_ids = sorted(set(args.mandala_id))
    else:
        selected_ids = find_mandala_ids(assets_root)

    selected_ids = list(selected_ids)
    if not selected_ids:
        raise RuntimeError("No mandala ids found to process.")

    if args.output_name and len(selected_ids) != 1:
        raise ValueError("--output-name can only be used with a single --mandala-id")

    if args.output_name and (args.include_hard or args.hard_only):
        raise ValueError("--output-name cannot be combined with --include-hard or --hard-only")

    if args.hard_only and not args.include_hard:
        args.include_hard = True

    generated_paths: List[Path] = []
    for mandala_id in selected_ids:
        if not args.hard_only:
            output_path = process_mandala(assets_root, mandala_id, args.output_name, hard_mode=False)
            generated_paths.append(output_path)

        if args.include_hard:
            asset_dir = assets_root / str(mandala_id)
            if has_hard_adjacency_file(asset_dir, mandala_id):
                output_path = process_mandala(assets_root, mandala_id, None, hard_mode=True)
                generated_paths.append(output_path)
            elif args.hard_only:
                raise FileNotFoundError(
                    f"Mandala {mandala_id} has no hard adjacency JSON, cannot use --hard-only"
                )

    print(f"Generated {len(generated_paths)} MiniZinc file(s):")
    for path in generated_paths:
        print(f" - {path}")


if __name__ == "__main__":
    main()
