#!/usr/bin/env python3
"""
Generate MiniZinc graph-coloring models from mandala region/adjacency C++ files.

The generated model minimizes the number of colors while ensuring adjacent
regions never share the same color.

By default, this script auto-discovers mandala ids under:
  - app/src/database/<id>/<id>_regions.cpp
  - app/src/database/<id>/<id>_adjacency.cpp

For each discovered id, it writes a .mzn file next to the asset JSON files:
  - resources/assets/<id>/mandala_<id>.mzn (or based on existing mandala_*.json)
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Iterable, List, Sequence, Set, Tuple


Edge = Tuple[int, int]


def parse_region_ids(regions_cpp_path: Path) -> Set[int]:
    text = regions_cpp_path.read_text(encoding="utf-8")
    pattern = re.compile(r"regions\.emplace_back\(\s*(\d+)\s*,")
    return {int(match.group(1)) for match in pattern.finditer(text)}


def parse_adjacency_edges(adjacency_cpp_path: Path) -> Set[Edge]:
    text = adjacency_cpp_path.read_text(encoding="utf-8")
    pattern = re.compile(r"addAdjacency\(\s*(\d+)\s*,\s*(\d+)\s*\)")

    edges: Set[Edge] = set()
    for match in pattern.finditer(text):
        a = int(match.group(1))
        b = int(match.group(2))
        if a == b:
            continue
        edges.add((a, b) if a < b else (b, a))

    return edges


def find_mandala_ids(database_root: Path) -> List[int]:
    ids: List[int] = []
    for child in database_root.iterdir():
        if not child.is_dir() or not child.name.isdigit():
            continue

        mandala_id = int(child.name)
        regions_cpp = child / f"{mandala_id}_regions.cpp"
        adjacency_cpp = child / f"{mandala_id}_adjacency.cpp"
        if regions_cpp.exists() and adjacency_cpp.exists():
            ids.append(mandala_id)

    return sorted(ids)


def infer_output_filename(asset_dir: Path, mandala_id: int) -> str:
    direct_name = f"mandala_{mandala_id}.json"
    direct_path = asset_dir / direct_name
    if direct_path.exists():
        return direct_path.stem + ".mzn"

    candidates = sorted(asset_dir.glob("mandala_*.json"))
    if len(candidates) == 1:
        return candidates[0].stem + ".mzn"

    return f"mandala_{mandala_id}.mzn"


def format_int_set(values: Sequence[int]) -> str:
    return "{" + ", ".join(str(value) for value in values) + "}"


def format_int_array(values: Sequence[int]) -> str:
    return "[" + ", ".join(str(value) for value in values) + "]"


def build_minizinc_model(region_ids: Sequence[int], edges: Sequence[Edge], source_note: str) -> str:
    if not region_ids:
        raise ValueError("No region ids found.")

    first_region = region_ids[0]
    edge_u = [edge[0] for edge in edges]
    edge_v = [edge[1] for edge in edges]

    lines: List[str] = []
    lines.append(f"% Auto-generated by tools/generate_minizinc.py from {source_note}")
    lines.append("% Objective: minimize number of colors used for the mandala graph.")
    lines.append("")
    lines.append(f"set of int: REGIONS = {format_int_set(region_ids)};")
    lines.append(f"int: REGION_COUNT = {len(region_ids)};")
    lines.append(f"int: EDGE_COUNT = {len(edges)};")
    lines.append("")
    lines.append("array[REGIONS] of var 1..REGION_COUNT: color;")
    lines.append("var 1..REGION_COUNT: max_color;")
    lines.append("")
    if edges:
        lines.append("array[1..EDGE_COUNT] of int: edge_u = " + format_int_array(edge_u) + ";")
        lines.append("array[1..EDGE_COUNT] of int: edge_v = " + format_int_array(edge_v) + ";")
        lines.append("")
        lines.append("constraint forall(e in 1..EDGE_COUNT)(color[edge_u[e]] != color[edge_v[e]]);")

    lines.append("constraint forall(r in REGIONS)(color[r] <= max_color);")
    lines.append(f"constraint color[{first_region}] = 1;")
    lines.append("")
    lines.append("solve :: int_search([color[r] | r in REGIONS], first_fail, indomain_min, complete) minimize max_color;")
    lines.append("")
    lines.append(
        'output ["min_colors=", show(max_color), "\\n", '
        '"colors=", show([color[r] | r in REGIONS]), "\\n"];'
    )

    return "\n".join(lines) + "\n"


def process_mandala(database_root: Path, assets_root: Path, mandala_id: int, output_name: str | None) -> Path:
    source_dir = database_root / str(mandala_id)
    regions_cpp = source_dir / f"{mandala_id}_regions.cpp"
    adjacency_cpp = source_dir / f"{mandala_id}_adjacency.cpp"

    if not regions_cpp.exists():
        raise FileNotFoundError(f"Missing regions file: {regions_cpp}")
    if not adjacency_cpp.exists():
        raise FileNotFoundError(f"Missing adjacency file: {adjacency_cpp}")

    region_ids = parse_region_ids(regions_cpp)
    edges = parse_adjacency_edges(adjacency_cpp)

    ids_from_edges = {id_value for edge in edges for id_value in edge}
    all_ids = sorted(region_ids | ids_from_edges)
    sorted_edges = sorted(edges)

    asset_dir = assets_root / str(mandala_id)
    asset_dir.mkdir(parents=True, exist_ok=True)

    output_filename = output_name if output_name else infer_output_filename(asset_dir, mandala_id)
    output_path = asset_dir / output_filename

    source_note = f"{regions_cpp.relative_to(database_root.parent)} and {adjacency_cpp.relative_to(database_root.parent)}"
    model = build_minizinc_model(all_ids, sorted_edges, source_note)
    output_path.write_text(model, encoding="utf-8")

    return output_path


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent

    parser = argparse.ArgumentParser(
        description=(
            "Generate MiniZinc models for mandala graph coloring from "
            "<id>_regions.cpp and <id>_adjacency.cpp files."
        )
    )
    parser.add_argument(
        "--database-root",
        type=Path,
        default=project_root / "app" / "src" / "database",
        help="Path to app/src/database (default: project app/src/database)",
    )
    parser.add_argument(
        "--assets-root",
        type=Path,
        default=project_root / "resources" / "assets",
        help="Path to resources/assets (default: project resources/assets)",
    )
    parser.add_argument(
        "--mandala-id",
        type=int,
        action="append",
        help="Mandala id to process. Repeat option to process multiple ids.",
    )
    parser.add_argument(
        "--output-name",
        type=str,
        help="Optional output filename for single-id generation (example: mandala_1.mzn)",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    database_root: Path = args.database_root.resolve()
    assets_root: Path = args.assets_root.resolve()

    if not database_root.exists():
        raise FileNotFoundError(f"Database root does not exist: {database_root}")

    selected_ids: Iterable[int]
    if args.mandala_id:
        selected_ids = sorted(set(args.mandala_id))
    else:
        selected_ids = find_mandala_ids(database_root)

    if not selected_ids:
        raise RuntimeError("No mandala ids found to process.")

    if args.output_name and len(list(selected_ids)) != 1:
        raise ValueError("--output-name can only be used with a single --mandala-id")

    generated_paths: List[Path] = []
    for mandala_id in selected_ids:
        output_path = process_mandala(database_root, assets_root, mandala_id, args.output_name)
        generated_paths.append(output_path)

    print(f"Generated {len(generated_paths)} MiniZinc file(s):")
    for path in generated_paths:
        print(f" - {path}")


if __name__ == "__main__":
    main()
